version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file:
      - db.env
    ports:
      - '5432:5432'  
    volumes:
      - postgres_data:/var/lib/postgresql/data
  service:
    build: app
    container_name: django_app
    expose:
      - "8000"
    volumes:
      - static_volume:/opt/app/static
  nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static:ro
    depends_on:
      - service
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume: